/*
 * Copyright (c) 2017 Oticon A/S
 * Copyright (c) 2023 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdint.h>
#include <stddef.h>

/**
 * Bitwise reverse 1 byte,
 * Based on code in the public domain as claimed by the author in this page:
 * http://graphics.stanford.edu/~seander/bithacks.html#ReverseByteWith64Bits
 */
static uint8_t rev_byte(uint8_t input){
  return ((input * 0x80200802ULL) & 0x0884422110ULL)
          * 0x0101010101ULL >> 32;
}

/**
 * Reverse the bits order in a 32 bit word
 */
static uint32_t rev_32(uint32_t input){
  uint32_t ret;
  ret = rev_byte((input >> 0) & 0xff) << 24
      | rev_byte((input >> 8) & 0xff) << 16
      | rev_byte((input >> 16) & 0xff) << 8
      | rev_byte((input >> 24) & 0xff);
  return ret;
}

/**
 * Reverse the bits order in a 24 bit word
 */
static uint32_t rev_24(uint32_t input){
  uint32_t ret;
  ret = rev_byte((input >> 0) & 0xff) << 16
      | rev_byte((input >> 8) & 0xff) << 8
      | rev_byte((input >> 16) & 0xff);
  return ret;
}

/**
 * Reverse the bits order in a 16 bit word
 */
static uint32_t rev_16(uint16_t input){
  uint16_t ret;
  ret = rev_byte((input >> 0) & 0xff) << 8
      | rev_byte((input >> 8) & 0xff) << 0;
  return ret;
}

/*
 Table implementation of the CRCs autogenerated with these scripts (with very minor modifications)
 https://pycrc.org (These python scripts are MIT licensed)
 Options="--std=C99 --width=24 --poly=0x100065B --algorithm=table-driven --xor-out=0x0 --xor-in=0x555555 --reflect-in=true --reflect-out=true --crc-type=uint32_t"
 python pycrc.py $Options --generate=h > pycrc_stdout.h
 python pycrc.py $Options --generate=c-main  > pycrc_stdout.c
 gcc pycrc_stdout.c -o testexe && ./testexe -s "@"
 */
static const uint32_t crc_table_24_ble[256] = {
    0x000000, 0x01b4c0, 0x036980, 0x02dd40, 0x06d300, 0x0767c0, 0x05ba80, 0x040e40,
    0x0da600, 0x0c12c0, 0x0ecf80, 0x0f7b40, 0x0b7500, 0x0ac1c0, 0x081c80, 0x09a840,
    0x1b4c00, 0x1af8c0, 0x182580, 0x199140, 0x1d9f00, 0x1c2bc0, 0x1ef680, 0x1f4240,
    0x16ea00, 0x175ec0, 0x158380, 0x143740, 0x103900, 0x118dc0, 0x135080, 0x12e440,
    0x369800, 0x372cc0, 0x35f180, 0x344540, 0x304b00, 0x31ffc0, 0x332280, 0x329640,
    0x3b3e00, 0x3a8ac0, 0x385780, 0x39e340, 0x3ded00, 0x3c59c0, 0x3e8480, 0x3f3040,
    0x2dd400, 0x2c60c0, 0x2ebd80, 0x2f0940, 0x2b0700, 0x2ab3c0, 0x286e80, 0x29da40,
    0x207200, 0x21c6c0, 0x231b80, 0x22af40, 0x26a100, 0x2715c0, 0x25c880, 0x247c40,
    0x6d3000, 0x6c84c0, 0x6e5980, 0x6fed40, 0x6be300, 0x6a57c0, 0x688a80, 0x693e40,
    0x609600, 0x6122c0, 0x63ff80, 0x624b40, 0x664500, 0x67f1c0, 0x652c80, 0x649840,
    0x767c00, 0x77c8c0, 0x751580, 0x74a140, 0x70af00, 0x711bc0, 0x73c680, 0x727240,
    0x7bda00, 0x7a6ec0, 0x78b380, 0x790740, 0x7d0900, 0x7cbdc0, 0x7e6080, 0x7fd440,
    0x5ba800, 0x5a1cc0, 0x58c180, 0x597540, 0x5d7b00, 0x5ccfc0, 0x5e1280, 0x5fa640,
    0x560e00, 0x57bac0, 0x556780, 0x54d340, 0x50dd00, 0x5169c0, 0x53b480, 0x520040,
    0x40e400, 0x4150c0, 0x438d80, 0x423940, 0x463700, 0x4783c0, 0x455e80, 0x44ea40,
    0x4d4200, 0x4cf6c0, 0x4e2b80, 0x4f9f40, 0x4b9100, 0x4a25c0, 0x48f880, 0x494c40,
    0xda6000, 0xdbd4c0, 0xd90980, 0xd8bd40, 0xdcb300, 0xdd07c0, 0xdfda80, 0xde6e40,
    0xd7c600, 0xd672c0, 0xd4af80, 0xd51b40, 0xd11500, 0xd0a1c0, 0xd27c80, 0xd3c840,
    0xc12c00, 0xc098c0, 0xc24580, 0xc3f140, 0xc7ff00, 0xc64bc0, 0xc49680, 0xc52240,
    0xcc8a00, 0xcd3ec0, 0xcfe380, 0xce5740, 0xca5900, 0xcbedc0, 0xc93080, 0xc88440,
    0xecf800, 0xed4cc0, 0xef9180, 0xee2540, 0xea2b00, 0xeb9fc0, 0xe94280, 0xe8f640,
    0xe15e00, 0xe0eac0, 0xe23780, 0xe38340, 0xe78d00, 0xe639c0, 0xe4e480, 0xe55040,
    0xf7b400, 0xf600c0, 0xf4dd80, 0xf56940, 0xf16700, 0xf0d3c0, 0xf20e80, 0xf3ba40,
    0xfa1200, 0xfba6c0, 0xf97b80, 0xf8cf40, 0xfcc100, 0xfd75c0, 0xffa880, 0xfe1c40,
    0xb75000, 0xb6e4c0, 0xb43980, 0xb58d40, 0xb18300, 0xb037c0, 0xb2ea80, 0xb35e40,
    0xbaf600, 0xbb42c0, 0xb99f80, 0xb82b40, 0xbc2500, 0xbd91c0, 0xbf4c80, 0xbef840,
    0xac1c00, 0xada8c0, 0xaf7580, 0xaec140, 0xaacf00, 0xab7bc0, 0xa9a680, 0xa81240,
    0xa1ba00, 0xa00ec0, 0xa2d380, 0xa36740, 0xa76900, 0xa6ddc0, 0xa40080, 0xa5b440,
    0x81c800, 0x807cc0, 0x82a180, 0x831540, 0x871b00, 0x86afc0, 0x847280, 0x85c640,
    0x8c6e00, 0x8ddac0, 0x8f0780, 0x8eb340, 0x8abd00, 0x8b09c0, 0x89d480, 0x886040,
    0x9a8400, 0x9b30c0, 0x99ed80, 0x985940, 0x9c5700, 0x9de3c0, 0x9f3e80, 0x9e8a40,
    0x972200, 0x9696c0, 0x944b80, 0x95ff40, 0x91f100, 0x9045c0, 0x929880, 0x932c40
};

static uint32_t crc_update_ble(uint32_t crc, const void *data, size_t data_len)
{
  const unsigned char *d = (const unsigned char *)data;
  unsigned int tbl_idx;

  while (data_len--) {
    tbl_idx = (crc ^ *d) & 0xff;
    crc = (crc_table_24_ble[tbl_idx] ^ (crc >> 8)) & 0xffffff;

    d++;
  }
  return crc & 0xffffff;
}

/*
 * Bitwise implementation of the 24bit BLE CRC
 * CAREFULL:
 *   * The CRC value is bitwise reversed compared to what the BLE standard sends in air
 *   * Data is expected right aligned (i.e. if data_len_b = 1, data is in the LSB)
 */
static uint32_t crc_update_ble24_b(uint32_t crc, const void *data, int data_len_b)
{
    const unsigned char *d = (const unsigned char *)data;
    unsigned int i;
    uint32_t bit;
    unsigned char c;

    while (data_len_b) {
        c = *d++;
        for (i = 0x01; (i & 0xff) && (data_len_b > 0); i <<= 1, data_len_b--) {
            bit = (crc & 0x800000) ^ ((c & i) ? 0x800000 : 0);
            crc <<= 1;
            if (bit) {
                crc ^= 0x00065b;
            }
        }
        crc &= 0xffffff;
    }
    return crc & 0xffffff;
}

/**
 * Append the BLE CRC to a buffer buf of len bytes at the end of the buffer
 * itself
 */
void append_crc_ble(uint8_t* buf, unsigned int len, uint32_t crc_init)
{
  uint32_t crc;
  crc = crc_update_ble(rev_24(crc_init), buf, len);

  /* Copy CRC itself at the end of the input buffer */
  for (int i = 0; i < 3; i++) {
    buf[len + i] = (crc >> (i*8)) & 0xff;
  }
  return;
}

/**
 * Calculate (and return) the BLE CRC for an input buffer <buf> of <len> *bits*
 * Where the data is ordered from LSB to MSB
 * Note: The CRC is returned in the order expected by BLE (bitwise reversed)
 *
 * If you know your input length is a multiple number of bytes, use append_crc_ble()
 * or crc_update_ble() instead (it is faster).
 */
uint32_t calc_crc_ble24_b(uint8_t* buf, unsigned int len, uint32_t crc_init)
{
  uint32_t crc;
  crc = rev_24(crc_update_ble(rev_24(crc_init), buf, len/8 ));
  crc = rev_24(crc_update_ble24_b(crc, &buf[len/8], len - (len/8)*8));

  return crc;
}

/*
 Table implementation of the CRCs autogenerated with these scripts (with very minor modifications)
 https://pycrc.org (These python scripts are MIT licensed)
 Options="--std=C99 --width=32 --poly=0x104C11DB7 --algorithm=table-driven --reflect-in=true --reflect-out=true --crc-type=uint32_t"
 python pycrc.py $Options --generate=h > pycrc_stdout.h
 python pycrc.py $Options --generate=c-main  > pycrc_stdout.c
 gcc pycrc_stdout.c -o testexe && ./testexe -s "@"
 */
static const uint32_t crc_table_32_ble[256] = {
    0x00000000, 0x77073096, 0xee0e612c, 0x990951ba, 0x076dc419, 0x706af48f, 0xe963a535, 0x9e6495a3,
    0x0edb8832, 0x79dcb8a4, 0xe0d5e91e, 0x97d2d988, 0x09b64c2b, 0x7eb17cbd, 0xe7b82d07, 0x90bf1d91,
    0x1db71064, 0x6ab020f2, 0xf3b97148, 0x84be41de, 0x1adad47d, 0x6ddde4eb, 0xf4d4b551, 0x83d385c7,
    0x136c9856, 0x646ba8c0, 0xfd62f97a, 0x8a65c9ec, 0x14015c4f, 0x63066cd9, 0xfa0f3d63, 0x8d080df5,
    0x3b6e20c8, 0x4c69105e, 0xd56041e4, 0xa2677172, 0x3c03e4d1, 0x4b04d447, 0xd20d85fd, 0xa50ab56b,
    0x35b5a8fa, 0x42b2986c, 0xdbbbc9d6, 0xacbcf940, 0x32d86ce3, 0x45df5c75, 0xdcd60dcf, 0xabd13d59,
    0x26d930ac, 0x51de003a, 0xc8d75180, 0xbfd06116, 0x21b4f4b5, 0x56b3c423, 0xcfba9599, 0xb8bda50f,
    0x2802b89e, 0x5f058808, 0xc60cd9b2, 0xb10be924, 0x2f6f7c87, 0x58684c11, 0xc1611dab, 0xb6662d3d,
    0x76dc4190, 0x01db7106, 0x98d220bc, 0xefd5102a, 0x71b18589, 0x06b6b51f, 0x9fbfe4a5, 0xe8b8d433,
    0x7807c9a2, 0x0f00f934, 0x9609a88e, 0xe10e9818, 0x7f6a0dbb, 0x086d3d2d, 0x91646c97, 0xe6635c01,
    0x6b6b51f4, 0x1c6c6162, 0x856530d8, 0xf262004e, 0x6c0695ed, 0x1b01a57b, 0x8208f4c1, 0xf50fc457,
    0x65b0d9c6, 0x12b7e950, 0x8bbeb8ea, 0xfcb9887c, 0x62dd1ddf, 0x15da2d49, 0x8cd37cf3, 0xfbd44c65,
    0x4db26158, 0x3ab551ce, 0xa3bc0074, 0xd4bb30e2, 0x4adfa541, 0x3dd895d7, 0xa4d1c46d, 0xd3d6f4fb,
    0x4369e96a, 0x346ed9fc, 0xad678846, 0xda60b8d0, 0x44042d73, 0x33031de5, 0xaa0a4c5f, 0xdd0d7cc9,
    0x5005713c, 0x270241aa, 0xbe0b1010, 0xc90c2086, 0x5768b525, 0x206f85b3, 0xb966d409, 0xce61e49f,
    0x5edef90e, 0x29d9c998, 0xb0d09822, 0xc7d7a8b4, 0x59b33d17, 0x2eb40d81, 0xb7bd5c3b, 0xc0ba6cad,
    0xedb88320, 0x9abfb3b6, 0x03b6e20c, 0x74b1d29a, 0xead54739, 0x9dd277af, 0x04db2615, 0x73dc1683,
    0xe3630b12, 0x94643b84, 0x0d6d6a3e, 0x7a6a5aa8, 0xe40ecf0b, 0x9309ff9d, 0x0a00ae27, 0x7d079eb1,
    0xf00f9344, 0x8708a3d2, 0x1e01f268, 0x6906c2fe, 0xf762575d, 0x806567cb, 0x196c3671, 0x6e6b06e7,
    0xfed41b76, 0x89d32be0, 0x10da7a5a, 0x67dd4acc, 0xf9b9df6f, 0x8ebeeff9, 0x17b7be43, 0x60b08ed5,
    0xd6d6a3e8, 0xa1d1937e, 0x38d8c2c4, 0x4fdff252, 0xd1bb67f1, 0xa6bc5767, 0x3fb506dd, 0x48b2364b,
    0xd80d2bda, 0xaf0a1b4c, 0x36034af6, 0x41047a60, 0xdf60efc3, 0xa867df55, 0x316e8eef, 0x4669be79,
    0xcb61b38c, 0xbc66831a, 0x256fd2a0, 0x5268e236, 0xcc0c7795, 0xbb0b4703, 0x220216b9, 0x5505262f,
    0xc5ba3bbe, 0xb2bd0b28, 0x2bb45a92, 0x5cb36a04, 0xc2d7ffa7, 0xb5d0cf31, 0x2cd99e8b, 0x5bdeae1d,
    0x9b64c2b0, 0xec63f226, 0x756aa39c, 0x026d930a, 0x9c0906a9, 0xeb0e363f, 0x72076785, 0x05005713,
    0x95bf4a82, 0xe2b87a14, 0x7bb12bae, 0x0cb61b38, 0x92d28e9b, 0xe5d5be0d, 0x7cdcefb7, 0x0bdbdf21,
    0x86d3d2d4, 0xf1d4e242, 0x68ddb3f8, 0x1fda836e, 0x81be16cd, 0xf6b9265b, 0x6fb077e1, 0x18b74777,
    0x88085ae6, 0xff0f6a70, 0x66063bca, 0x11010b5c, 0x8f659eff, 0xf862ae69, 0x616bffd3, 0x166ccf45,
    0xa00ae278, 0xd70dd2ee, 0x4e048354, 0x3903b3c2, 0xa7672661, 0xd06016f7, 0x4969474d, 0x3e6e77db,
    0xaed16a4a, 0xd9d65adc, 0x40df0b66, 0x37d83bf0, 0xa9bcae53, 0xdebb9ec5, 0x47b2cf7f, 0x30b5ffe9,
    0xbdbdf21c, 0xcabac28a, 0x53b39330, 0x24b4a3a6, 0xbad03605, 0xcdd70693, 0x54de5729, 0x23d967bf,
    0xb3667a2e, 0xc4614ab8, 0x5d681b02, 0x2a6f2b94, 0xb40bbe37, 0xc30c8ea1, 0x5a05df1b, 0x2d02ef8d
};

static uint32_t crc_update_ble32(uint32_t crc, const void *data, size_t data_len)
{
  const unsigned char *d = (const unsigned char *)data;
  unsigned int tbl_idx;

  while (data_len--) {
    tbl_idx = (crc ^ *d) & 0xff;
    crc = (crc_table_32_ble[tbl_idx] ^ (crc >> 8));

    d++;
  }
  return crc;
}


/**
 * Append the BLE CRC to a buffer buf of len bytes at the end of the buffer
 * itself
 */
void append_crc_ble32(uint8_t* buf, unsigned int len, uint32_t crc_init)
{
  uint32_t crc;
  crc = crc_update_ble32(rev_32(crc_init), buf, len);

  /*Copy CRC itself at the end of the input buffer*/
  for (int i = 0; i < 4; i++) {
    buf[len + i] = (crc >> (i*8)) & 0xff;
  }
  return;
}


/*
 Table implementation of the CRCs autogenerated with these scripts (with very minor changes)
 https://pycrc.org (These python scripts are MIT licensed)
 mkdir pycrc && cd pycrc
 git clone git@github.com:tpircher/pycrc.git .

 Options="--std=C99 --width=16 --poly=0x1021 --algorithm=table-driven --reflect-in=true --reflect-out=true --crc-type=uint16_t"
 python3 src/pycrc.py $Options --generate=h > pycrc_stdout.h
 python3 src/pycrc.py $Options --generate=c-main  > pycrc_stdout.c
*/
static const uint16_t crc_table_154[256] = {
    0x0000, 0x1189, 0x2312, 0x329b, 0x4624, 0x57ad, 0x6536, 0x74bf,
    0x8c48, 0x9dc1, 0xaf5a, 0xbed3, 0xca6c, 0xdbe5, 0xe97e, 0xf8f7,
    0x1081, 0x0108, 0x3393, 0x221a, 0x56a5, 0x472c, 0x75b7, 0x643e,
    0x9cc9, 0x8d40, 0xbfdb, 0xae52, 0xdaed, 0xcb64, 0xf9ff, 0xe876,
    0x2102, 0x308b, 0x0210, 0x1399, 0x6726, 0x76af, 0x4434, 0x55bd,
    0xad4a, 0xbcc3, 0x8e58, 0x9fd1, 0xeb6e, 0xfae7, 0xc87c, 0xd9f5,
    0x3183, 0x200a, 0x1291, 0x0318, 0x77a7, 0x662e, 0x54b5, 0x453c,
    0xbdcb, 0xac42, 0x9ed9, 0x8f50, 0xfbef, 0xea66, 0xd8fd, 0xc974,
    0x4204, 0x538d, 0x6116, 0x709f, 0x0420, 0x15a9, 0x2732, 0x36bb,
    0xce4c, 0xdfc5, 0xed5e, 0xfcd7, 0x8868, 0x99e1, 0xab7a, 0xbaf3,
    0x5285, 0x430c, 0x7197, 0x601e, 0x14a1, 0x0528, 0x37b3, 0x263a,
    0xdecd, 0xcf44, 0xfddf, 0xec56, 0x98e9, 0x8960, 0xbbfb, 0xaa72,
    0x6306, 0x728f, 0x4014, 0x519d, 0x2522, 0x34ab, 0x0630, 0x17b9,
    0xef4e, 0xfec7, 0xcc5c, 0xddd5, 0xa96a, 0xb8e3, 0x8a78, 0x9bf1,
    0x7387, 0x620e, 0x5095, 0x411c, 0x35a3, 0x242a, 0x16b1, 0x0738,
    0xffcf, 0xee46, 0xdcdd, 0xcd54, 0xb9eb, 0xa862, 0x9af9, 0x8b70,
    0x8408, 0x9581, 0xa71a, 0xb693, 0xc22c, 0xd3a5, 0xe13e, 0xf0b7,
    0x0840, 0x19c9, 0x2b52, 0x3adb, 0x4e64, 0x5fed, 0x6d76, 0x7cff,
    0x9489, 0x8500, 0xb79b, 0xa612, 0xd2ad, 0xc324, 0xf1bf, 0xe036,
    0x18c1, 0x0948, 0x3bd3, 0x2a5a, 0x5ee5, 0x4f6c, 0x7df7, 0x6c7e,
    0xa50a, 0xb483, 0x8618, 0x9791, 0xe32e, 0xf2a7, 0xc03c, 0xd1b5,
    0x2942, 0x38cb, 0x0a50, 0x1bd9, 0x6f66, 0x7eef, 0x4c74, 0x5dfd,
    0xb58b, 0xa402, 0x9699, 0x8710, 0xf3af, 0xe226, 0xd0bd, 0xc134,
    0x39c3, 0x284a, 0x1ad1, 0x0b58, 0x7fe7, 0x6e6e, 0x5cf5, 0x4d7c,
    0xc60c, 0xd785, 0xe51e, 0xf497, 0x8028, 0x91a1, 0xa33a, 0xb2b3,
    0x4a44, 0x5bcd, 0x6956, 0x78df, 0x0c60, 0x1de9, 0x2f72, 0x3efb,
    0xd68d, 0xc704, 0xf59f, 0xe416, 0x90a9, 0x8120, 0xb3bb, 0xa232,
    0x5ac5, 0x4b4c, 0x79d7, 0x685e, 0x1ce1, 0x0d68, 0x3ff3, 0x2e7a,
    0xe70e, 0xf687, 0xc41c, 0xd595, 0xa12a, 0xb0a3, 0x8238, 0x93b1,
    0x6b46, 0x7acf, 0x4854, 0x59dd, 0x2d62, 0x3ceb, 0x0e70, 0x1ff9,
    0xf78f, 0xe606, 0xd49d, 0xc514, 0xb1ab, 0xa022, 0x92b9, 0x8330,
    0x7bc7, 0x6a4e, 0x58d5, 0x495c, 0x3de3, 0x2c6a, 0x1ef1, 0x0f78
};

uint16_t crc_update_154(uint16_t crc, const void *data, size_t data_len)
{
    const unsigned char *d = (const unsigned char *)data;
    unsigned int tbl_idx;

    while (data_len--) {
        tbl_idx = (crc ^ *d) & 0xff;
        crc = (crc_table_154[tbl_idx] ^ (crc >> 8)) & 0xffff;
        d++;
    }
    return crc & 0xffff;
}

/**
 * Append the 154 CRC to a buffer buf of len bytes at the end of the buffer
 * itself
 */
void append_crc_154(uint8_t* buf, unsigned int len, uint16_t crc_init)
{
  uint16_t crc;
  crc = crc_update_154( rev_16(crc_init), buf, len );

  /*Copy CRC itself at the end of the input buffer*/
  for (int i = 0; i < 2; i++) {
    buf[len + i] = (crc >> (i*8)) & 0xff;
  }
  return;
}

#if defined(__TEST_CRC_154)
//Quick unit test of the 154 CRC
// gcc -D__TEST_CRC_154 crc.c -o crc_154test && ./crc_154test
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

//An acknowledgment frame with no payload and the following 3 byte MHR (spec example)
//  0100 0000 0000 0000 0101 0110 (b0..b23)
uint8_t test_data[] = {0x2, 0x0, 0x6A};
//Expected CRC: 0010 0111 1001 1110 r0..r15
uint8_t test_crc[] = {0xE4, 0x79};

int main(){
  uint8_t buffer[10] = {0};
  memcpy(buffer, test_data, 3);

  append_crc_154(buffer, 3, 0x0);
  for (int i=0 ; i < 5; i++){
    printf("0x%02X ", buffer[i]);
  }
  printf("\n");

  if ((buffer[3] == test_crc[0]) && (buffer[4] == test_crc[1])){
    printf("CRC was correct -> PASSED\n");
    return 0;
  } else {
    printf("CRC NOT was correct -> FAILED \n");
    return 1;
  }
}
#endif //defined(__TEST_CRC_154)

#if 0
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

void print_crc(uint32_t crc) {
  for (int i=0 ; i < 3; i++){
    printf("0x%02X ", ((uint8_t*)&crc)[i]);
  }
  printf("\n");
}

uint8_t test_data[] = {0x02, 0x0, 0x6A, 0x53};

int main() {
  uint8_t buffer[sizeof(test_data)+3] = {0};
  uint8_t buffer2[sizeof(test_data)+3] = {0};
  uint8_t buffer3[sizeof(test_data)+3] = {0};
  uint8_t buffer4[sizeof(test_data)+3] = {0};
  uint len = sizeof(test_data);
  uint crc_init = 0x25;

  memcpy(buffer, test_data, len);

  append_crc_ble(buffer, len, crc_init); //Table impl.

  uint32_t crc1, crc2, crc3;
  { //New bitwise API processing all msg in one go
    crc1 = calc_crc_ble24_b(test_data, len*8, crc_init);
  }
  { //New API iterating bit-wise
    uint8_t d = 0;
    crc2 = crc_init;
    for (int i = 0; i < len*8; i++) {
      d = (test_data[i/8] >> (i%8)) & 0x1;
      crc2 = crc_update_ble24_b(crc2, &d, 1);
    }
    crc2 = rev_24(crc2);
  }
  { //New API iterating byte-wise
    crc3 = crc_init;
    for (int i = 0; i < len; i++) {
      crc3 = crc_update_ble24_b(crc3, &test_data[i], 8);
    }
    crc3 = rev_24(crc3);
  }

  for (int i=0 ; i < len +3; i++){
    printf("0x%02X ", buffer[i]);
  }
  printf("\n");

  print_crc(crc1);
  print_crc(crc2);
  print_crc(crc3);
}
#endif
